version: '3.5'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}


networks:
  backend:
    name: cartografia-network
    driver: bridge

volumes: 
  mongo_data:
  rabbit_data: