version: '3'
services:
  gateway:
    build: .
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
      
networks:
  backend:
    driver: bridge