version: '3'
services:
  gateway-dev:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    hostname: gateway
    volumes: 
      - .:/var/www/gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on: 
      - rabbitmq
  gateway:
    build: 
      context: .
      dockerfile: prod.Dockerfile
    hostname: gateway
    volumes: 
      - .:/var/www/gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on: 
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
      
networks:
  backend:
    name: cartografia-network
    driver: bridge
  
volumes: 
  node_modules: