version: '3.5'
services:
  gateway:
    build:
      context: ../.
      dockerfile: Dockerfile
    hostname: gateway
    command: npm run start:prod
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    external:
      name: cartografia-network