name: CD-hom

on:
  push:
    branches: [ develop, support/configuring-deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Digital Ocean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd projects/2021.1-Cartografia-social-api-gateway
          docker-compose -f deploy/hom/docker-compose.yml down
          git checkout support/configuring-deploy
          git pull origin support/configuring-deploy -f
          docker-compose -f deploy/hom/microsservices-compose.yml --env-file deploy/hom/.env.hom up -d --build
          docker-compose -f deploy/hom/docker-compose.yml --env-file deploy/hom/.env.hom up -d --build